### ISSUE TITLE
Xcode Build Failure

### ISSUE THREAD

**Issue by mentalcairns** [cwhitney/GoldsprintsFx#25]
<img width="803" alt="Screen Shot 2019-03-15 at 11 32 19 PM" src="https://user-images.githubusercontent.com/48506176/54471190-c2207500-477a-11e9-8196-df7f9beb7578.png">
Hi Charlie,

Xcode is unable to build my project due to the following error:

/clang:-1: no such file or directory: '../../..//libs/Cinder/lib/macosx/Debug/libcinder.a'

I manually copied the file from Cinder to the and got a successful build. Did I miss something or the repository missing the file? Checking <>Code, it seem it's missing. 

Thoughts?

**Comment by cwhitney** [comment]
Sorry to nto address this sooner, the problem is that cinder itself needed to be built.  Cinder compiles down to a `.a` file which Silversprints then links against so that it doesn't need to compile the entirety of cinder each time.  

There are instructions on how to build here: https://libcinder.org/docs/guides/git/index.html
